### ISSUE TITLE
Style2Vec: Representation Learning for Fashion Items from Style Sets

### ISSUE THREAD

**Issue by shunk031** [shunk031/paper-survey#118]
https://arxiv.org/abs/1708.04014

**Comment by shunk031** [comment]
https://shunk031.github.io/paper-survey/paper-summary/CV/Style2Vec_Representation_Learning_for_Fashion_Items_from_Style_Sets

**Comment by kargarisaac** [comment]
Hi,
Is the code for the style2vec available?
